# Generated by Django 4.2.1 on 2024-02-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_region_office_region'),
        ('api_integration', '0004_alter_integrationclientdetails_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationclientdetails',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='integration_client_details+', to='accounts.office'),
        ),
    ]
