# Generated by Django 4.2.1 on 2024-03-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_subaccount_vendors'),
        ('api_integration', '0005_alter_integrationclientdetails_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationclientdetails',
            options={},
        ),
        migrations.RemoveField(
            model_name='integrationclientdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='integrationclientdetails',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='integrationclientdetails',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_client_details', to='accounts.office'),
        ),
    ]
