# Generated by Django 4.2.1 on 2023-06-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0083_update_search_vectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendororder",
            name="submitted_to_vendor_site",
            field=models.BooleanField(default=False),
        ),
    ]
