# Generated by Django 4.2.1 on 2023-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0084_vendororder_ordered_on_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
