# Generated by Django 4.1.5 on 2023-06-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0085_product_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('processing', 'Ordo Order - Processing'), ('ordo', 'Ordo Order'), ('vendor', 'Vendor Direct')], default='processing', max_length=100),
        ),
    ]
