# Generated by Django 4.2.1 on 2023-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0086_alter_order_order_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="budget_spend_type",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="vendororderproduct",
            name="budget_spend_type",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
