# Generated by Django 4.2.1 on 2023-07-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0087_alter_cart_budget_spend_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="budget_spend_type",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
