# Generated by Django 4.2.1 on 2023-07-17 23:41

from django.db import migrations

MAT_VIEW_SQL = """
CREATE MATERIALIZED VIEW product_words AS
SELECT op.parent_id as product_id,
       array_to_string(tsvector_to_array(to_tsvector('simple', string_agg(
           op.name ||
           coalesce(op.product_id, '') ||
           coalesce(replace(op.product_id, '-', ''), '') ||
           coalesce(replace(op.manufacturer_number, '-', ''), '') ||
           coalesce(op.manufacturer_number, '') ||
           coalesce(op.sku, '') ||
           coalesce(replace(op.sku, '-', ''), ''),
       ' '))), ' ') as words
FROM orders_product op
WHERE op.parent_id IS NOT NULL AND vendor_id != 5
GROUP BY op.parent_id
"""


INDEX_SQL = """
CREATE INDEX ON product_words USING gin (words gin_trgm_ops);
"""
class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0088_alter_cart_budget_spend_type"),
    ]

    operations = [
        migrations.RunSQL(MAT_VIEW_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(INDEX_SQL, migrations.RunSQL.noop)
    ]
