# Generated by Django 4.2.1 on 2023-07-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0089_search_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductWords",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("words", models.TextField()),
            ],
            options={
                "db_table": "product_words",
                "managed": False,
            },
        ),
    ]
