# Generated by Django 4.2.1 on 2023-08-08 15:09

from django.db import migrations

FILL_BUDGET_SPEND_TYPE_SQL = """
WITH calculated_spend_type as (SELECT vop.id,
                                      CASE
                                          WHEN av.slug IN ('amazon', 'office_depot', 'staples') THEN 'office'
                                          ELSE 'dental'
                                          END as new_budget_spend_type
                               FROM orders_vendororderproduct vop
                                        JOIN orders_vendororder vo ON vop.vendor_order_id = vo.id
                                        JOIN accounts_vendor av ON vo.vendor_id = av.id
                               WHERE budget_spend_type IS NULL)
UPDATE orders_vendororderproduct
SET budget_spend_type = cst.new_budget_spend_type
FROM calculated_spend_type cst
    WHERE orders_vendororderproduct.id = cst.id;
"""
class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0090_productwords"),
    ]

    operations = [
        migrations.RunSQL(FILL_BUDGET_SPEND_TYPE_SQL, migrations.RunSQL.noop)
    ]
