# Generated by Django 4.2.1 on 2023-08-17 19:58

from django.db import migrations

DROP_SQL = """
DROP MATERIALIZED VIEW product_words;
"""

RECREATE_SQL = """
CREATE MATERIALIZED VIEW product_words AS
SELECT op.parent_id                                 as product_id,
       array_to_string(tsvector_to_array(to_tsvector('simple', string_agg(
                                       op.name || ' ' ||
                                       coalesce(op.product_id, '') || ' ' ||
                                       coalesce(replace(op.product_id, '-', ''), '') || ' ' ||
                                       coalesce(replace(op.manufacturer_number, '-', ''), '') || ' ' ||
                                       coalesce(op.manufacturer_number, '') || ' ' ||
                                       coalesce(op.sku, '') || ' ' ||
                                       coalesce(replace(op.sku, '-', ''), ''),
                                       ' '))), ' ') as words
FROM orders_product op
WHERE op.parent_id IS NOT NULL
  AND vendor_id != 5
GROUP BY op.parent_id
"""

class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0092_alter_vendororderproduct_budget_spend_type"),
    ]

    operations = [
        migrations.RunSQL(DROP_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(RECREATE_SQL, migrations.RunSQL.noop),
    ]
