# Generated by Django 4.2.1 on 2023-08-17 19:58

from django.db import migrations

DROP_SQL = """
DROP MATERIALIZED VIEW product_words;
"""

RECREATE_SQL = """
CREATE MATERIALIZED VIEW product_words AS
SELECT op.parent_id                                 as product_id,
       array_to_string(tsvector_to_array(to_tsvector('simple', string_agg(op.name, ' '))), ' ') as words,
       (SELECT array_agg(DISTINCT x) FROM unnest(
                                array_agg(op.product_id::text) ||
                                array_agg(op.manufacturer_number::text) ||
                                array_agg(op.sku::text) ||
                                array_agg(replace(op.product_id::text, '-', '')) ||
                                array_agg(replace(op.manufacturer_number::text, '-', '')) ||
                                array_agg(replace(op.sku::text, '-', ''))
       ) t(x)
       WHERE x IS NOT NULL) as numbers,
       (SELECT array_agg(DISTINCT x) FROM unnest(array_agg(op.name::text)) t(x)
        WHERE x IS NOT NULL) as names
FROM orders_product op
WHERE op.parent_id IS NOT NULL
  AND vendor_id != 5
GROUP BY op.parent_id
"""

CREATE_INDEXES = """
CREATE INDEX ON product_words USING gin (words gin_trgm_ops);
CREATE INDEX ON product_words USING gin (numbers array_ops);
CREATE INDEX ON product_words USING gin (names array_ops);
"""

class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0093_update_materialized_view"),
    ]

    operations = [
        migrations.RunSQL(DROP_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(RECREATE_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(CREATE_INDEXES, migrations.RunSQL.noop),
    ]
