# Generated by Django 4.2.1 on 2023-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0095_add_product_price_age_materialized_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAge",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("office_name", models.CharField(max_length=200)),
                ("vendor_slug", models.CharField(max_length=200)),
                (
                    "age_group",
                    models.IntegerField(
                        choices=[(1, "<1d"), (2, "<3d"), (3, "<7d"), (4, "<15d"), (5, "<30d"), (6, ">30d")]
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "price_age",
                "managed": False,
            },
        ),
    ]
