# Generated by Django 4.2.1 on 2024-02-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_region_office_region'),
        ('orders', '0097_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('office', 'product')},
        ),
    ]
