# Generated by Django 4.2.1 on 2023-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_officevendor_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
