# Generated by Django 4.2.1 on 2023-06-05 18:57

import django.db.models.deletion
from django.db import migrations, models

import apps.common.month.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_vendor_is_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", apps.common.month.models.MonthField()),
                ("adjusted_production", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("collection", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "basis",
                    models.IntegerField(choices=[(0, "No basis"), (1, "Adjusted Production"), (2, "Collection")]),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.office", related_name="budget_set"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subaccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("spend", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="subaccounts", to="accounts.budget"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vendors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("henry_schein", "henry_schein"),
                                ("darby", "darby"),
                                ("patterson", "patterson"),
                                ("amazon", "amazon"),
                                ("benco", "benco"),
                                ("ultradent", "ultradent"),
                                ("implant_direct", "implant_direct"),
                                ("edge_endo", "edge_endo"),
                                ("dental_city", "dental_city"),
                                ("dcdental", "dcdental"),
                                ("crazy_dental", "crazy_dental"),
                                ("purelife", "purelife"),
                                ("skydental", "skydental"),
                                ("top_glove", "top_glove"),
                                ("bluesky_bio", "bluesky_bio"),
                                ("practicon", "practicon"),
                                ("midwest_dental", "midwest_dental"),
                                ("pearson", "pearson"),
                                ("salvin", "salvin"),
                                ("bergmand", "bergmand"),
                                ("biohorizons", "biohorizons"),
                                ("atomo", "atomo"),
                                ("orthoarch", "orthoarch"),
                                ("office_depot", "office_depot"),
                                ("safco", "safco"),
                                ("net_32", "net_32"),
                            ]
                        ),
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
