# Generated by Django 4.2.1 on 2023-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_companymember_company"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(fields=("office", "month"), name="budget_office_month_uniq"),
        ),
        migrations.AddConstraint(
            model_name="subaccount",
            constraint=models.UniqueConstraint(fields=("budget", "slug"), name="subaccount_budget_slug_uniq"),
        ),
    ]
