# Generated by Django 4.2.1 on 2023-07-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0029_budget_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymember",
            name="invite_status",
            field=models.IntegerField(
                choices=[
                    (0, "Invite Sent"),
                    (1, "Invite Approved"),
                    (2, "Invite Declined"),
                    (3, "Invite Not Accepted"),
                ],
                default=0,
            ),
        ),
    ]
