# Generated by Django 4.2.1 on 2023-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_alter_companymember_invite_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="basis",
            field=models.IntegerField(
                choices=[(0, "No basis"), (1, "Adjusted Production"), (2, "Collection")], default=1
            ),
        ),
    ]
