# Generated by Django 4.2.1 on 2023-07-20 17:42

from django.db import migrations

SQL = """
create or replace function erase_company(p_company_id integer) returns void
    language plpgsql
as
$$
DECLARE
    creator_user_id int;
BEGIN
    DELETE FROM orders_procedure WHERE office_id IN (SELECT id FROM accounts_office WHERE company_id = p_company_id);

    DELETE FROM accounts_companymemberinviteschedule WHERE company_member_id IN (
        SELECT id FROM accounts_companymember WHERE company_id = p_company_id
    );

    DELETE FROM accounts_companymember WHERE company_id = p_company_id;

    DELETE FROM orders_officekeyword WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM orders_vendororderproduct
    WHERE vendor_order_id IN (
        SELECT id
        FROM orders_vendororder
        WHERE order_id in (
            SELECT id
            FROM orders_order
            WHERE office_id IN (
                SELECT id
                FROM accounts_office
                WHERE company_id = p_company_id
            )
        )
    );

    DELETE
    FROM orders_vendororder
    WHERE order_id in (
        SELECT id
        FROM orders_order
        WHERE office_id IN (
            SELECT id
            FROM accounts_office
            WHERE company_id = p_company_id
        )
    );

    DELETE FROM orders_order WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE FROM orders_cart WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE FROM orders_officecheckoutstatus
        WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM orders_officeproductcategory
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM orders_officeproduct
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_subscription
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_officevendor_shipping_options
        WHERE officevendor_id IN (
            SELECT id FROM accounts_officevendor
                      WHERE office_id IN (
                            SELECT id
                            FROM accounts_office
                            WHERE company_id = p_company_id
                      )
        );

    DELETE
    FROM accounts_officevendor
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_officesetting
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_officeaddress
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_officebudget
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_card
    WHERE office_id IN (
        SELECT id
        FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_subaccount
    WHERE budget_id IN (
        SELECT ab.id
        FROM accounts_budget ab
            JOIN accounts_office
            ON ab.office_id = accounts_office.id
        WHERE accounts_office.company_id = p_company_id
    );

    DELETE
    FROM accounts_budget
    WHERE office_id IN (
        SELECT id FROM accounts_office
        WHERE company_id = p_company_id
    );

    DELETE
    FROM accounts_office
    WHERE company_id = p_company_id;

    SELECT creator_id INTO creator_user_id FROM accounts_company WHERE id = p_company_id;

    DELETE FROM accounts_company WHERE id = p_company_id;

    DELETE FROM audit_searchhistory WHERE user_id = creator_user_id;

    DELETE FROM accounts_user WHERE id = creator_user_id;
END;
$$;
"""
class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_companymember_date_invited"),
    ]

    operations = [
        migrations.RunSQL(SQL, migrations.RunSQL.noop)
    ]
