# Generated by Django 4.2.1 on 2023-07-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_erase_company_function"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companymember",
            name="token_expires_at",
        ),
    ]
