# Generated by Django 4.2.1 on 2023-07-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_companymemberinviteschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymember",
            name="invite_status",
            field=models.IntegerField(choices=[(0, "Invite Sent"), (1, "Invite Approved")], default=0),
        ),
    ]
