# Generated by Django 4.2.1 on 2023-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_companymemberinviteschedule_scheduled_actual_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companymember",
            options={},
        ),
        migrations.AddConstraint(
            model_name="companymember",
            constraint=models.UniqueConstraint(fields=("email", "office"), name="email_office_unique"),
        ),
    ]
