# Generated by Django 4.2.1 on 2023-07-28 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_alter_companymember_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="creator",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
