# Generated by Django 4.2.1 on 2023-07-28 18:57

from django.db import migrations

FILL_CREATORS = """
WITH creators AS (SELECT DISTINCT ON (company_id) company_id, user_id
                  FROM accounts_companymember ac
                           JOIN accounts_company c ON ac.company_id = c.id
                  WHERE ac.user_id IS NOT NULL
                  ORDER BY ac.company_id, ac.created_at)
UPDATE accounts_company ac
SET creator_id = cr.user_id
FROM creators cr
WHERE ac.id = cr.company_id
"""

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_company_creator"),
    ]

    operations = [
        migrations.RunSQL(FILL_CREATORS, migrations.RunSQL.noop)
    ]
