# Generated by Django 4.2.1 on 2023-09-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_chart_to_sql"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officevendor",
            options={"ordering": ("vendor__name",), "verbose_name": "Unlinked Vendor"},
        ),
        migrations.CreateModel(
            name="OnboardingStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("offices_added", models.BooleanField(default=False)),
                ("subscribed", models.BooleanField(default=False)),
                ("vendors_linked", models.BooleanField(default=False)),
                ("budget_set", models.BooleanField(default=False)),
                ("team_invited", models.BooleanField(default=False)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_status",
                        to="accounts.company",
                    ),
                ),
            ],
        ),
    ]
