# Generated by Django 4.2.1 on 2023-09-06 13:23

from django.db import migrations


def create_onboarding_statuses(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    OnboardingStatus = apps.get_model("accounts", "OnboardingStatus")
    to_create = []
    for company_id in Company.objects.values_list("id", flat=True):
        status = OnboardingStatus(
            company_id=company_id,
            offices_added=True,
            subscribed=True,
            vendors_linked=True,
            budget_set=True,
            team_invited=True,
        )
        to_create.append(status)
    OnboardingStatus.objects.bulk_create(to_create)

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_alter_officevendor_options_onboardingstatus"),
    ]

    operations = [
        migrations.RunPython(create_onboarding_statuses, migrations.RunPython.noop)
    ]
