# Generated by Django 4.2.1 on 2023-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_update_erase_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.IntegerField(choices=[(0, 'Owner'), (1, 'Admin'), (2, 'User'), (3, 'Mid Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Owner'), (1, 'Admin'), (2, 'User'), (3, 'Mid Admin')], default=1),
        ),
    ]
