# Generated by Django 4.2.1 on 2023-11-09 10:52

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_companymember_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True,
                                                                   editable=False, populate_from=['name'])),
                ('is_active', models.BooleanField(default=True)),
                ('billing_together', models.BooleanField(default=False)),
                ('ghosted', models.DateTimeField(blank=True, null=True)),
                ('company', apps.common.models.FlexibleForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sub_companies', to='accounts.company')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Companies',
            },
        ),
    ]
