# Generated by Django 4.2.1 on 2023-11-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0050_subcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='sub_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='sub_offices', to='accounts.subcompany'),
        ),
    ]
