# Generated by Django 4.2.1 on 2023-11-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_update_erase_company'),
        ('accounts', '0051_office_sub_company'),
    ]

    operations = [
    ]
