# Generated by Django 4.2.1 on 2023-12-06 08:57

import apps.common.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_unlinkedofficevendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='officevendor',
            name='company',
            field=apps.common.models.FlexibleForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_company', to='accounts.company'),
        ),
    ]
