# Generated by Django 4.2.1 on 2024-02-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_officevendor_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='officevendor',
            unique_together=set(),
        ),
    ]
