# Generated by Django 4.2.1 on 2024-03-11 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_region_office_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='vendors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('henry_schein', 'henry_schein'), ('darby', 'darby'), ('patterson', 'patterson'), ('amazon', 'amazon'), ('benco', 'benco'), ('ultradent', 'ultradent'), ('implant_direct', 'implant_direct'), ('edge_endo', 'edge_endo'), ('dental_city', 'dental_city'), ('dcdental', 'dcdental'), ('purelife', 'purelife'), ('skydental', 'skydental'), ('top_glove', 'top_glove'), ('bluesky_bio', 'bluesky_bio'), ('practicon', 'practicon'), ('midwest_dental', 'midwest_dental'), ('pearson', 'pearson'), ('salvin', 'salvin'), ('bergmand', 'bergmand'), ('biohorizons', 'biohorizons'), ('atomo', 'atomo'), ('orthoarch', 'orthoarch'), ('office_depot', 'office_depot'), ('safco', 'safco'), ('staples', 'staples'), ('net_32', 'net_32'), ('crazy_dental', 'crazy_dental')]), default=list, size=None),
        ),
    ]
