# Generated by Django 4.2.1 on 2024-03-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('accounts', '0057_alter_subaccount_vendors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='officevendor',
            unique_together={('office', 'vendor')},
        ),
    ]
