# Generated by Django 4.2.1 on 2023-11-16 11:28

import datetime

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(blank=True, max_length=512, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date(2023, 11, 23))),
                ('users',
                 models.IntegerField(choices=[(0, 'All'), (1, 'Admin'), (3, 'Sub Admin'), (2, 'User')], default=0)),
                ('once', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('background_color', colorfield.fields.ColorField(default='#ff1dc3', image_field=None, max_length=25,
                                                                  samples=[('#ff1dc3', 'pink'), ('#FF0000', 'red'),
                                                ('#00FF00', 'green'), ('#0000FF', 'blue')])),
                ('foreground_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25,
                                                                  samples=[('#ffffff', 'white'), ('#000000', 'black'),
                                                                           ('#FF0000', 'red'), ('#00FF00', 'green')])),
            ],
            options={
                'verbose_name_plural': 'Greetings',
            },
        ),
    ]
