# Generated by Django 4.2.1 on 2023-11-20 12:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greetings',
            name='end_date',
            field=models.DateField(
                default=datetime.datetime(2023, 11, 27, 12, 27, 2, 668831, tzinfo=datetime.timezone.utc)),
        ),
    ]
