# Generated by Django 4.2.1 on 2023-11-21 13:24

from django.db import migrations, models

import apps.greetings.models


class Migration(migrations.Migration):

    dependencies = [
        ("greetings", "0002_alter_greetings_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="greetings",
            name="end_date",
            field=models.DateField(default=apps.greetings.models.after_seven_days),
        ),
    ]
