# Generated by Django 4.2.1 on 2023-11-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={'verbose_name_plural': 'Wait Lists'},
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='provided_coupen',
        ),
    ]
